services:
    postgres:
        container_name: postgres
        image: postgres
        volumes:
            - storage_db:/var/lib/postgres/data
        networks:
            - app
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}

    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        networks:
            - app
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DB_USER}@admin.com
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
        ports:
            - "5050:80"

    node:
        container_name: node
        build: ./
        restart: always
        networks:
            - app
        ports:
            -   "3000:3000"
        depends_on:
            -   postgres
        env_file:
            -   ./.env

volumes:
  storage_db:

networks:
    app:
        driver: bridge